### ISSUE TITLE
Prodigal failing on short sequences

### ISSUE THREAD

**Issue by AlessioMilanese** [zellerlab/stag#32]
If you run `stag classify_genome` on a small fasta file, I get:
```
Unzip the database
('COG0012', '5490')
('COG0016', '6345')
('COG0018', '9315')
('COG0172', '7155')
('COG0215', '10530')
('COG0495', '18660')
('COG0525', '30105')
('COG0533', '17565')
('COG0541', '10965')
('COG0552', '5010')
Run prodigal
Traceback (most recent call last):
  File "/nile/DB/milanese/CONDA/miniconda3.9/envs/stag0.8.2/bin/stag", line 8, in <module>
    sys.exit(main())
  File "/nile/DB/milanese/CONDA/miniconda3.9/envs/stag0.8.2/lib/python3.9/site-packages/stag/__main__.py", line 582, in main
    classify_genome.classify_genome(args.database, genome_files=list_files, marker_genes=marker_genes,
  File "/nile/DB/milanese/CONDA/miniconda3.9/envs/stag0.8.2/lib/python3.9/site-packages/stag/classify_genome.py", line 429, in classify_genome
    genomes_pred = run_prodigal_genomes(genome_files)
  File "/nile/DB/milanese/CONDA/miniconda3.9/envs/stag0.8.2/lib/python3.9/site-packages/stag/classify_genome.py", line 96, in run_prodigal_genomes
    return {genome: run_prodigal(genome) for genome in genome_files}
  File "/nile/DB/milanese/CONDA/miniconda3.9/envs/stag0.8.2/lib/python3.9/site-packages/stag/classify_genome.py", line 96, in <dictcomp>
    return {genome: run_prodigal(genome) for genome in genome_files}
  File "/nile/DB/milanese/CONDA/miniconda3.9/envs/stag0.8.2/lib/python3.9/site-packages/stag/classify_genome.py", line 74, in run_prodigal
    raise ValueError(f"[E::align] Error. prodigal failed\n\n{all_stderr}")
ValueError: [E::align] Error. prodigal failed

-------------------------------------
PRODIGAL v2.6.3 [February, 2016]         
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------
Request:  Single Genome, Phase:  Training
Reading in the sequence(s) to train...

Error:  Sequence must be 20000 characters (only 1489 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
```

**Comment by AlessioMilanese** [comment]
Also, note that when we run `stag classify_genome` with the `-D` option, the computation will stop when it encounter the small fasta file. 
The desired result would be to skip the short genome and still finish the analysis of the other genomes.
